# Generated by Django 5.2 on 2025-04-20 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('window_title', models.CharField(blank=True, max_length=255, null=True)),
                ('clipboard', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('analysis', models.TextField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AppUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(max_length=1024)),
                ('operation', models.CharField(max_length=50)),
                ('process_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='USBDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_name', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
