# Generated by Django 5.2 on 2025-04-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='screenshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appusagelog',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appusagelog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appusagelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fileaccesslog',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fileaccesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usbdevicelog',
            name='product_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usbdevicelog',
            name='serial_number',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usbdevicelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usbdevicelog',
            name='vendor_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='websitevisitlog',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='websitevisitlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
