# Generated by Django 5.2 on 2025-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_activitylog_options_alter_activitylog_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usbdevicelog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
